# Generated by Django 6.0.6 on 2026-06-27 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('utility_bills_paid', models.IntegerField(default=0)),
                ('telecom_history_months', models.IntegerField(default=0)),
                ('micro_loan_rejections', models.IntegerField(default=0)),
                ('hmac_signature', models.CharField(help_text='SHA-256 signature from Edge SDK', max_length=256)),
                ('calculated_trust_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
