# Generated by Django 6.0.6 on 2026-06-27 08:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Row creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC).')),
                ('hashed_key', models.CharField(help_text='HMAC-SHA256 digest of the API key (hex-encoded, 64 chars).', max_length=128, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text="Human-readable label (e.g. 'production', 'staging').", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Revoke a credential without deleting the audit trail.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful authentication.', null=True)),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
                'db_table': 'finedge_api_credential',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Row creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC).')),
                ('name', models.CharField(help_text='Legal entity name of the bank / NBFC.', max_length=255)),
                ('tenant_code', models.CharField(db_index=True, help_text="Short, URL-safe code identifying the tenant (e.g. 'hdfc', 'axis_nbfc').  Used in API routing.", max_length=50, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-disable flag.  Inactive tenants cannot submit new sessions.')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'finedge_bank',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Row creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC).')),
                ('computed_charge', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Charge for this API call (INR).', max_digits=10)),
                ('processing_cycle_stamp', models.CharField(db_index=True, help_text="Billing cycle identifier (YYYY-MM format, e.g. '2026-06').", max_length=7)),
                ('description', models.CharField(blank=True, default='', help_text="Human-readable billing note (e.g. 'TrustScore computation').", max_length=255)),
                ('bank', models.ForeignKey(help_text='Tenant being billed.', on_delete=django.db.models.deletion.PROTECT, related_name='billing_entries', to='api_gateway.bank')),
            ],
            options={
                'verbose_name': 'Billing Ledger Entry',
                'verbose_name_plural': 'Billing Ledger Entries',
                'db_table': 'finedge_billing_ledger',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Row creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC).')),
                ('tracking_reference', models.CharField(db_index=True, help_text="Client-supplied idempotency / tracking reference (e.g. partner's internal loan-application ID).", max_length=100, unique=True)),
                ('current_step', models.CharField(choices=[('sdk_received', 'SDK Data Received'), ('vector_validated', 'Vector Validated'), ('score_computed', 'TrustScore Computed'), ('decision_rendered', 'Decision Rendered'), ('fallback_review', 'Fallback Manual Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('error', 'Processing Error')], db_index=True, default='sdk_received', help_text='Current position in the scoring waterfall.', max_length=30)),
                ('bank', models.ForeignKey(help_text='Tenant that submitted this application.', on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='api_gateway.bank')),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'db_table': 'finedge_loan_application',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SdkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Row creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC).')),
                ('device_hash_mask', models.CharField(db_index=True, help_text='SHA-256 hash of the device hardware identifiers.  Used for session deduplication without storing PII.', max_length=128)),
                ('bank', models.ForeignKey(help_text='Tenant that owns this session.', on_delete=django.db.models.deletion.PROTECT, related_name='sdk_sessions', to='api_gateway.bank')),
            ],
            options={
                'verbose_name': 'SDK Session',
                'verbose_name_plural': 'SDK Sessions',
                'db_table': 'finedge_sdk_session',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustScoreResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Row creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC).')),
                ('mathematical_vector', models.JSONField(help_text='Raw feature vector from the Edge SDK.  Schema: {device_age_days, utility_sms_count, battery_deaths_weekly, saved_contacts_ratio, financial_apps_count, average_monthly_balance, lifetime_emi_bounces}.')),
                ('calculated_score', models.IntegerField(help_text='XGBoost-derived TrustScore (300–900).', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)])),
                ('default_probability', models.FloatField(blank=True, help_text='Model-predicted probability of default [0.0, 1.0].', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('model_version', models.CharField(default='v1.0.0', help_text='Semantic version of the XGBoost model used for inference.', max_length=50)),
                ('is_thin_file', models.BooleanField(db_index=True, default=False, help_text='True if device_age_days < 14 — triggers the fallback manual-review route.')),
            ],
            options={
                'verbose_name': 'TrustScore Result',
                'verbose_name_plural': 'TrustScore Results',
                'db_table': 'finedge_trust_score_result',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LoanApplicant',
        ),
        migrations.AddField(
            model_name='apicredential',
            name='bank',
            field=models.ForeignKey(help_text='Owning tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='api_credentials', to='api_gateway.bank'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sdk_session',
            field=models.ForeignKey(help_text='SDK session that produced the feature vector.', on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='api_gateway.sdksession'),
        ),
        migrations.AddField(
            model_name='trustscoreresult',
            name='loan_application',
            field=models.OneToOneField(help_text='The loan application this score belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='trust_score', to='api_gateway.loanapplication'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.UniqueConstraint(fields=('bank', 'tracking_reference'), name='uq_bank_tracking_ref'),
        ),
    ]
