# Generated by Django 6.0.6 on 2026-06-27 09:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0002_apicredential_bank_billingledger_loanapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Row creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC).')),
                ('device_hash_mask', models.CharField(db_index=True, help_text='The hashed device identifier that was burned.', max_length=255)),
                ('status', models.CharField(default='BURNED', help_text='Status of this device hash (e.g. BURNED).', max_length=50)),
                ('reason', models.TextField(help_text='Reason for burning (e.g. Velocity lock).')),
            ],
            options={
                'verbose_name': 'Fraud Event',
                'verbose_name_plural': 'Fraud Events',
                'db_table': 'finedge_fraud_event',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
