# Generated by Django 6.0.6 on 2026-06-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='finedge_contact_message',
        ),
    ]
