# Generated by Django 6.0.6 on 2026-06-27 10:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0005_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='aa_status',
            field=models.CharField(default='pending', help_text='Account Aggregator status (e.g. pending, completed).', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cibil_score',
            field=models.IntegerField(default=-1, help_text='Traditional CIBIL score (-1 means New to Credit).'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Requested loan amount (defaulting to Mini Loan size).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='current_step',
            field=models.CharField(choices=[('sdk_received', 'SDK Data Received'), ('vector_validated', 'Vector Validated'), ('score_computed', 'TrustScore Computed'), ('decision_rendered', 'Decision Rendered'), ('fallback_review', 'Fallback Manual Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('error', 'Processing Error')], default='sdk_received', help_text='Current state in the underwriting pipeline.', max_length=50),
        ),
        migrations.AlterField(
            model_name='trustscoreresult',
            name='calculated_score',
            field=models.IntegerField(blank=True, help_text='XGBoost-derived TrustScore (300–900).', null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)]),
        ),
    ]
