# Generated by Django 5.0.3 on 2026-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0006_loanapplication_aa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='tenure_months',
            field=models.IntegerField(default=3, help_text='Requested tenure in months.'),
        ),
    ]
