# Generated by Django 5.0.3 on 2026-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0007_loanapplication_tenure_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_name',
            field=models.CharField(default='Demo User', help_text='Extracted name of the applicant.', max_length=150),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_phone',
            field=models.CharField(default='+91 0000000000', help_text='Extracted phone number.', max_length=20),
        ),
    ]
